GET http://localhost:3000/recipes.json
###Show item
GET http://localhost:3000/recipes/4.json

###Update
PATCH http://localhost:3000/recipes/1.json
Content-Type: application/json

{
 "name": "Avocado",
 "prep_time": "1",
 "ingredients": "Fresh Avocado",
 "instructions": "Grow nicely in the bayou"
}

###Delete
DELETE http://localhost:3000/recipes/7.json

###Create
POST http://localhost:3000/recipes.json
Content-Type: application/json

{
  "name": "Yogurt",
  "ingredients": "Milk and fermenter",
  "prep_time": "30",
  "instructions": "Mix milk and stir, cook evenly for 2 hours, swirl the shake up"
}